// Canonical Pokémon Champions roster.
// key   = internal app key (= normalize(display name), used everywhere in app logic)
// slug  = PokéAPI slug to fetch (defaults to key; null = fan-game form, use manual data)
// types = manual type array (fan-game forms only)
// speed = manual base speed  (fan-game forms only, null = unknown)

export const CHAMPIONS = [
  // ── Gen 1 base ────────────────────────────────────────────────────────────
  { key: "venusaur" },
  { key: "charizard" },
  { key: "blastoise" },
  { key: "beedrill" },
  { key: "pidgeot" },
  { key: "arbok" },
  { key: "pikachu" },
  { key: "raichu" },
  { key: "raichu-alola",    slug: "raichu-alola" },
  { key: "clefable" },
  { key: "ninetales" },
  { key: "ninetales-alola", slug: "ninetales-alola" },
  { key: "arcanine" },
  { key: "arcanine-hisui",  slug: "arcanine-hisui" },
  { key: "alakazam" },
  { key: "machamp" },
  { key: "victreebel" },
  { key: "slowbro" },
  { key: "slowbro-galar",   slug: "slowbro-galar" },
  { key: "gengar" },
  { key: "kangaskhan" },
  { key: "starmie" },
  { key: "pinsir" },
  { key: "tauros" },
  { key: "tauros-paldea-combat-breed", slug: "tauros-paldea-combat-breed" },
  { key: "tauros-paldea-blaze-breed",  slug: "tauros-paldea-blaze-breed" },
  { key: "tauros-paldea-aqua-breed",   slug: "tauros-paldea-aqua-breed" },
  { key: "gyarados" },
  { key: "ditto" },
  { key: "vaporeon" },
  { key: "jolteon" },
  { key: "flareon" },
  { key: "aerodactyl" },
  { key: "snorlax" },
  { key: "dragonite" },
  // ── Gen 2 ─────────────────────────────────────────────────────────────────
  { key: "meganium" },
  { key: "typhlosion" },
  { key: "typhlosion-hisui", slug: "typhlosion-hisui" },
  { key: "feraligatr" },
  { key: "ariados" },
  { key: "ampharos" },
  { key: "azumarill" },
  { key: "politoed" },
  { key: "espeon" },
  { key: "umbreon" },
  { key: "slowking" },
  { key: "slowking-galar",   slug: "slowking-galar" },
  { key: "forretress" },
  { key: "steelix" },
  { key: "scizor" },
  { key: "heracross" },
  { key: "skarmory" },
  { key: "houndoom" },
  { key: "tyranitar" },
  // ── Gen 3 ─────────────────────────────────────────────────────────────────
  { key: "pelipper" },
  { key: "gardevoir" },
  { key: "sableye" },
  { key: "aggron" },
  { key: "medicham" },
  { key: "manectric" },
  { key: "sharpedo" },
  { key: "camerupt" },
  { key: "torkoal" },
  { key: "altaria" },
  { key: "milotic" },
  { key: "castform" },
  { key: "banette" },
  { key: "chimecho" },
  { key: "absol" },
  { key: "glalie" },
  // ── Gen 4 ─────────────────────────────────────────────────────────────────
  { key: "torterra" },
  { key: "infernape" },
  { key: "empoleon" },
  { key: "luxray" },
  { key: "roserade" },
  { key: "rampardos" },
  { key: "bastiodon" },
  { key: "lopunny" },
  { key: "spiritomb" },
  { key: "garchomp" },
  { key: "lucario" },
  { key: "hippowdon" },
  { key: "toxicroak" },
  { key: "abomasnow" },
  { key: "weavile" },
  { key: "rhyperior" },
  { key: "leafeon" },
  { key: "glaceon" },
  { key: "gliscor" },
  { key: "mamoswine" },
  { key: "gallade" },
  { key: "froslass" },
  { key: "rotom" },
  { key: "rotom-heat",  slug: "rotom-heat" },
  { key: "rotom-wash",  slug: "rotom-wash" },
  { key: "rotom-frost", slug: "rotom-frost" },
  { key: "rotom-fan",   slug: "rotom-fan" },
  { key: "rotom-mow",   slug: "rotom-mow" },
  // ── Gen 5 ─────────────────────────────────────────────────────────────────
  { key: "serperior" },
  { key: "emboar" },
  { key: "samurott" },
  { key: "samurott-hisui", slug: "samurott-hisui" },
  { key: "watchog" },
  { key: "liepard" },
  { key: "simisage" },
  { key: "simisear" },
  { key: "simipour" },
  { key: "excadrill" },
  { key: "audino" },
  { key: "conkeldurr" },
  { key: "whimsicott" },
  { key: "krookodile" },
  { key: "cofagrigus" },
  { key: "garbodor" },
  { key: "zoroark" },
  { key: "zoroark-hisui", slug: "zoroark-hisui" },
  { key: "reuniclus" },
  { key: "vanilluxe" },
  { key: "emolga" },
  { key: "chandelure" },
  { key: "beartic" },
  { key: "stunfisk" },
  { key: "stunfisk-galar", slug: "stunfisk-galar" },
  { key: "golurk" },
  { key: "hydreigon" },
  { key: "volcarona" },
  // ── Gen 6 ─────────────────────────────────────────────────────────────────
  { key: "chesnaught" },
  { key: "delphox" },
  { key: "greninja" },
  { key: "diggersby" },
  { key: "talonflame" },
  { key: "vivillon" },
  { key: "floette-eternal", slug: "floette-eternal" },
  { key: "florges" },
  { key: "pangoro" },
  { key: "furfrou" },
  { key: "meowstic",   slug: "meowstic-male" },
  { key: "meowstic-f", slug: "meowstic-female" },
  { key: "aegislash", slug: "aegislash-shield" },
  { key: "aromatisse" },
  { key: "slurpuff" },
  { key: "clawitzer" },
  { key: "heliolisk" },
  { key: "tyrantrum" },
  { key: "aurorus" },
  { key: "sylveon" },
  { key: "hawlucha" },
  { key: "dedenne" },
  { key: "goodra" },
  { key: "goodra-hisui", slug: "goodra-hisui" },
  { key: "klefki" },
  { key: "trevenant" },
  { key: "gourgeist",       slug: "gourgeist-average" },
  { key: "gourgeist-small", slug: "gourgeist-small" },
  { key: "gourgeist-large", slug: "gourgeist-large" },
  { key: "gourgeist-super", slug: "gourgeist-super" },
  { key: "avalugg" },
  { key: "avalugg-hisui", slug: "avalugg-hisui" },
  { key: "noivern" },
  // ── Gen 7 ─────────────────────────────────────────────────────────────────
  { key: "decidueye" },
  { key: "decidueye-hisui", slug: "decidueye-hisui" },
  { key: "incineroar" },
  { key: "primarina" },
  { key: "toucannon" },
  { key: "crabominable" },
  { key: "lycanroc",          slug: "lycanroc-midday" },
  { key: "lycanroc-midnight", slug: "lycanroc-midnight" },
  { key: "lycanroc-dusk",     slug: "lycanroc-dusk" },
  { key: "toxapex" },
  { key: "mudsdale" },
  { key: "araquanid" },
  { key: "salazzle" },
  { key: "tsareena" },
  { key: "oranguru" },
  { key: "passimian" },
  { key: "mimikyu", slug: "mimikyu-disguised" },
  { key: "drampa" },
  { key: "kommo-o" },
  // ── Gen 8 ─────────────────────────────────────────────────────────────────
  { key: "corviknight" },
  { key: "flapple" },
  { key: "appletun" },
  { key: "sandaconda" },
  { key: "polteageist" },
  { key: "hatterene" },
  { key: "mr-rime",   slug: "mr-rime" },
  { key: "runerigus" },
  { key: "alcremie" },
  { key: "morpeko", slug: "morpeko-full-belly" },
  { key: "dragapult" },
  // ── Gen 8 Hisui ───────────────────────────────────────────────────────────
  { key: "wyrdeer" },
  { key: "kleavor" },
  { key: "basculegion-male",   slug: "basculegion-male" },
  { key: "basculegion-female", slug: "basculegion-female" },
  { key: "sneasler" },
  // ── Gen 9 ─────────────────────────────────────────────────────────────────
  { key: "meowscarada" },
  { key: "skeledirge" },
  { key: "quaquaval" },
  { key: "maushold", slug: "maushold-family-of-three" },
  { key: "garganacl" },
  { key: "armarouge" },
  { key: "ceruledge" },
  { key: "bellibolt" },
  { key: "scovillain" },
  { key: "espathra" },
  { key: "tinkaton" },
  { key: "palafin", slug: "palafin-zero" },
  { key: "orthworm" },
  { key: "glimmora" },
  { key: "farigiraf" },
  { key: "kingambit" },
  { key: "sinistcha" },
  { key: "archaludon" },
  { key: "hydrapple" },

  // ── Mega Evolutions (in PokéAPI) ──────────────────────────────────────────
  { key: "venusaur-mega",    slug: "venusaur-mega" },
  { key: "charizard-mega-x", slug: "charizard-mega-x" },
  { key: "charizard-mega-y", slug: "charizard-mega-y" },
  { key: "blastoise-mega",   slug: "blastoise-mega" },
  { key: "beedrill-mega",    slug: "beedrill-mega" },
  { key: "pidgeot-mega",     slug: "pidgeot-mega" },
  { key: "alakazam-mega",    slug: "alakazam-mega" },
  { key: "slowbro-mega",     slug: "slowbro-mega" },
  { key: "gengar-mega",      slug: "gengar-mega" },
  { key: "kangaskhan-mega",  slug: "kangaskhan-mega" },
  { key: "pinsir-mega",      slug: "pinsir-mega" },
  { key: "gyarados-mega",    slug: "gyarados-mega" },
  { key: "aerodactyl-mega",  slug: "aerodactyl-mega" },
  { key: "ampharos-mega",    slug: "ampharos-mega" },
  { key: "steelix-mega",     slug: "steelix-mega" },
  { key: "scizor-mega",      slug: "scizor-mega" },
  { key: "heracross-mega",   slug: "heracross-mega" },
  { key: "houndoom-mega",    slug: "houndoom-mega" },
  { key: "tyranitar-mega",   slug: "tyranitar-mega" },
  { key: "gardevoir-mega",   slug: "gardevoir-mega" },
  { key: "sableye-mega",     slug: "sableye-mega" },
  { key: "aggron-mega",      slug: "aggron-mega" },
  { key: "medicham-mega",    slug: "medicham-mega" },
  { key: "manectric-mega",   slug: "manectric-mega" },
  { key: "sharpedo-mega",    slug: "sharpedo-mega" },
  { key: "camerupt-mega",    slug: "camerupt-mega" },
  { key: "altaria-mega",     slug: "altaria-mega" },
  { key: "banette-mega",     slug: "banette-mega" },
  { key: "absol-mega",       slug: "absol-mega" },
  { key: "glalie-mega",      slug: "glalie-mega" },
  { key: "lopunny-mega",     slug: "lopunny-mega" },
  { key: "garchomp-mega",    slug: "garchomp-mega" },
  { key: "lucario-mega",     slug: "lucario-mega" },
  { key: "abomasnow-mega",   slug: "abomasnow-mega" },
  { key: "gallade-mega",     slug: "gallade-mega" },
  { key: "audino-mega",      slug: "audino-mega" },

  // ── Fan-game Mega Evolutions (not in PokéAPI) ─────────────────────────────
  { key: "clefable-mega",   slug: null, types: ["fairy"],              speed: 80 },
  { key: "victreebel-mega", slug: null, types: ["grass","poison"],     speed: 80 },
  { key: "starmie-mega",    slug: null, types: ["water","psychic"],    speed: 120 },
  { key: "dragonite-mega",  slug: null, types: ["dragon","flying"],    speed: 100 },
  { key: "meganium-mega",   slug: null, types: ["grass"],              speed: 80 },
  { key: "feraligatr-mega", slug: null, types: ["water"],              speed: 78 },
  { key: "skarmory-mega",   slug: null, types: ["steel","flying"],     speed: 70 },
  { key: "chimecho-mega",   slug: null, types: ["psychic"],            speed: 65 },
  { key: "froslass-mega",   slug: null, types: ["ice","ghost"],        speed: 120 },
  { key: "emboar-mega",     slug: null, types: ["fire","fighting"],    speed: 65 },
  { key: "excadrill-mega",  slug: null, types: ["steel","ground"],     speed: 88 },
  { key: "chandelure-mega", slug: null, types: ["ghost","fire"],       speed: 80 },
  { key: "golurk-mega",     slug: null, types: ["ground","ghost"],     speed: 55 },
  { key: "chesnaught-mega", slug: null, types: ["grass","fighting"],   speed: 64 },
  { key: "delphox-mega",    slug: null, types: ["fire","psychic"],     speed: 134 },
  { key: "greninja-mega",   slug: null, types: ["water","dark"],       speed: 122 },
];
